name: Build and Deployed Code

on:  [push,pull-request]

jobs:
  job1:
    env:
        DATABASE_HOSTNAME=localhost
        DATABASE_PORT=5432
        DATABASE_PASSWORD=123qwe
        DATABASE_NAME=fastapi
        DATABASE_USERNAME=postgres
        SECRET_KEY=d7gdsfgsfd7896gsdhgsdh87fdbvcklsadgljkjkoicv6174bvnidflhuibbgv
        ALGORITHM=HS256
        ACCESS_TOKEN_EXPIRATION_MINUTES=30
    runs-on: ubuntu-latest
    steps:
    - name: pulling git reports
      uses: actions/checkout@v2
    - name: install python latest
      uses: checkout/setup-python@v2
      with:
        python-version: "3.10"
    - name: update pip
      run: python -m pip install --upgrade pip
    - name : install all dependencies
      run: pip install -r requirements.txt
    